<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<!--AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault-->
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" />
		<PackageReference Include="Avalonia.Controls.ItemsRepeater" />
		<PackageReference Include="Avalonia.Themes.Fluent" />
		<PackageReference Include="Avalonia.Fonts.Inter" />
		<PackageReference Include="Avalonia.Controls.DataGrid" />
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Dock.Avalonia" />
		<PackageReference Include="Dock.Avalonia.Themes.Fluent" />
		<PackageReference Include="Dock.Model.Avalonia" />
		<PackageReference Include="Dock.Model.Mvvm" />
		<PackageReference Include="Avalonia.AvaloniaEdit" />
		<PackageReference Include="AvaloniaEdit.TextMate" />
		<PackageReference Include="Microsoft.Extensions.ObjectPool" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ATuimStudio.Common\ATuimStudio.Common.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Build.Ui\ATuimStudio.Extensions.Build.Ui.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Core.Abstractions\ATuimStudio.Extensions.Core.Abstractions.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Core.Sqlite\ATuimStudio.Extensions.Core.Sqlite.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Core.Ui.Abstractions\ATuimStudio.Extensions.Core.Ui.Abstractions.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Core\ATuimStudio.Extensions.Core.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Debug.Ui\ATuimStudio.Extensions.Debug.Ui.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.Git.Ui\ATuimStudio.Extensions.Git.Ui.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.TextEditCompletion.Ui\ATuimStudio.Extensions.TextEditCompletion.Ui.csproj" />
		<ProjectReference Include="..\ATuimStudio.Extensions.TextEditReferences.Ui\ATuimStudio.Extensions.TextEditReferences.Ui.csproj" />
	</ItemGroup>
</Project>
